name: phanboichau_app
description: Centralized Application for Phan Boi Chau - Cam Ranh.
publish_to: 'none'
version: 1.3.2+12

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  advance_pdf_viewer: ^1.2.0
  auto_route: ^0.6.9
  cloud_firestore: ^0.14.3
  dartz: ^0.9.2
  firebase_core: ^0.5.2
  flushbar: ^1.10.4
  flutter_bloc: ^6.1.1
  freezed_annotation: ^0.12.0
  get_it: ^5.0.1
  google_fonts: ^1.1.1
  horizontal_data_table: ^1.0.8
  injectable: ^1.0.5
  intl: ^0.16.1
  introduction_screen: ^1.0.9
  provider: ^4.3.2+2
  shared_preferences: ^0.5.12+2
  url_launcher: ^5.7.10

dev_dependencies:
  auto_route_generator: ^0.6.10
  build_runner: ^1.10.3
  flutter_launcher_icons: ^0.8.1
  freezed: ^0.12.2
  injectable_generator: ^1.0.6
  lint: ^1.3.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app/PBCCR.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/pdf/
